import marimo

__generated_with = "0.14.17"
app = marimo.App(width="medium")


@app.cell
def _():
    import marimo as mo
    import matplotlib.pyplot as plt
    import numpy as np
    return mo, np, plt


@app.cell
def _(mo):
    mo.md(
        r"""
        # Adam-DA in zero-sum games: an evidence-first tutorial

        **Observed central result:** in the audited interaction-dominated game,
        the maximum stable step size falls from **0.07712** at
        \(\beta=-0.3\) to **0.002907** at \(\beta=0.9\). This is the momentum
        reversal emphasized by arXiv 2605.19392.

        The arrays below are embedded from the completed CPU evidence run, so
        opening this notebook never retrains a model or reruns the expensive
        campaign.
        """
    )
    return


@app.cell
def _(np):
    beta = np.array([-0.3, 0.0, 0.3, 0.6, 0.9])
    stable_h = np.array(
        [0.0771225159, 0.0520993530, 0.0306160522, 0.0148697693, 0.0029074768]
    )
    rho = np.array([0.3, 0.5, 0.7, 0.9])
    rho_flatness = np.array([0.02886146, 0.02765537, 0.02551542, 0.02237406])
    beta_flatness = np.array(
        [0.55989742, 0.56078792, 0.56245442, 0.56669607, 0.59979274]
    )
    return beta, beta_flatness, rho, rho_flatness, stable_h


@app.cell
def _(beta, plt, stable_h):
    fig_stability, ax_stability = plt.subplots(figsize=(8, 4))
    ax_stability.plot(beta, stable_h, "o-", linewidth=3, color="#6941c6")
    ax_stability.set(
        xlabel="first-order momentum β",
        ylabel="maximum stable h",
        title="Smaller β permits a broader stable range",
    )
    ax_stability.grid(alpha=0.25)
    fig_stability
    return


@app.cell
def _(mo):
    mo.md(
        r"""
        ## What is being optimized?

        The clean-room game is

        \[
        f(x,y)=\tfrac12x^2+3xy-\tfrac12y^2,
        \]

        minimized in \(x\) and maximized in \(y\). Its game Jacobian has
        eigenvalues \(-1\pm3i\), so interaction dominates self-curvature.
        Adam-DA uses simultaneous, bias-corrected first and second moments.
        The formal verifier freezes the convergence predicate and changes only
        the committed experiment code between OpenResearch nodes.
        """
    )
    return


@app.cell
def _(beta, beta_flatness, plt, rho, rho_flatness):
    fig_flatness, axes_flatness = plt.subplots(1, 2, figsize=(9, 3.6))
    axes_flatness[0].plot(beta, beta_flatness, "o-", color="#d92d20")
    axes_flatness[0].set(xlabel="β", ylabel="cumulative ‖∇f‖₁", title="β sweep")
    axes_flatness[1].plot(rho, rho_flatness, "o-", color="#039855")
    axes_flatness[1].set(xlabel="ρ", title="ρ sweep")
    for axis in axes_flatness:
        axis.grid(alpha=0.25)
    fig_flatness.tight_layout()
    fig_flatness
    return


@app.cell
def _(mo):
    mo.md(
        r"""
        ## The truncation-error claim is measured directly

        Across four initial states and eight step sizes, the corrected modified
        ODE has mean log-log order **2.9961**. Removing the \(O(h)\)
        modified-equation correction produces order **1.9956**, an intentional
        negative control. The test aligns every discretization at physical time
        0.2 and checks the theorem's transient threshold.

        ## Honest boundary

        The ResNet/CNN CIFAR-10/STL-10 GAN claim is **BLOCKED**. The paper does
        not disclose enough information to identify a unique experiment, and
        the independently calibrated three-seed CPU campaign exceeds 337 hours
        before data loading and Inception evaluation. Four different
        verification/falsification routes were completed; none justifies
        replacing the named GAN experiment with a proxy.

        Formal evidence is generated by:

        ```bash
        uv run --locked python repro/src/verify.py
        ```

        Optional bounded exploration in this notebook uses only the embedded
        arrays above.
        """
    )
    return


if __name__ == "__main__":
    app.run()
